// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwFpAS1ZH7ve9UXdSZlx-UuIkqwe0g_U',
    appId: '1:132008349319:android:cdddb66dd4ab8557857222',
    messagingSenderId: '132008349319',
    projectId: 'collabsy-mobile-applicaation',
    storageBucket: 'collabsy-mobile-applicaation.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCakc6pwrTv7daRjCiuFb6R0FYq9AcWzqU',
    appId: '1:132008349319:ios:34674f735ec48ce6857222',
    messagingSenderId: '132008349319',
    projectId: 'collabsy-mobile-applicaation',
    storageBucket: 'collabsy-mobile-applicaation.firebasestorage.app',
    androidClientId: '132008349319-kfibc24205j91uttt8b216olq2jcr92s.apps.googleusercontent.com',
    iosClientId: '132008349319-kk9pu32l6aboj3pc9eaco1cd2hn1r8i6.apps.googleusercontent.com',
    iosBundleId: 'online.collabsy.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV74-c6R-QMmTj-NRBSpOg7pI2wsCW510',
    appId: '1:132008349319:web:66b3cf4586b601e2857222',
    messagingSenderId: '132008349319',
    projectId: 'collabsy-mobile-applicaation',
    authDomain: 'collabsy-mobile-applicaation.firebaseapp.com',
    storageBucket: 'collabsy-mobile-applicaation.firebasestorage.app',
    measurementId: 'G-CVL3VFNMPM',
  );
}
